v0.3

diff --git a/apidockerfile b/apidockerfile
--- a/apidockerfile
+++ b/apidockerfile
@@ -1,29 +1,63 @@
 FROM python:3.7.12-slim
 
-RUN apt-get update
-RUN apt-get upgrade -y
-RUN apt-get install git -y
-RUN apt-get install curl -y
+ARG UID=1000
+ARG USER=appuser
+ARG WORKDIR=/app
+ARG UVICORN_PORT="8000"
+ARG UVICORN_HOST="0.0.0.0"
+ARG UVICORN_ROOT_PATH=""
 
-RUN pip install pipenv
+## Install system packages
+RUN apt-get update \
+    && apt-get -y upgrade \
+    && apt-get -y install git curl python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 \
+    # required on ARM Mac
+    && [ "x$(arch)" = "xx86_64" ] || apt-get install -y libgeos-dev \
+    # clean-up
+    && apt-get clean && rm -r /var/lib/apt/lists
 
-COPY ./clinical-mdr-api/Pipfile /tmp
+# Install pipenv and upgrade setup tools system-wide
+RUN pip install --upgrade pip pipenv wheel \
+    # clean-up
+    && rm -rf ~/.cache
 
-RUN cd /tmp && pipenv lock && pipenv requirements > requirements.txt
-RUN pip install -r /tmp/requirements.txt
+## Create non-root user
+RUN useradd --home-dir /home/$USER --user-group --create-home --uid $UID $USER
 
-COPY ./clinical-mdr-api /tmp/cmdr
-WORKDIR /tmp/cmdr
+## Commands below run relative to this working directory
+WORKDIR $WORKDIR
 
-## add non root user and set permissions.
-RUN adduser appuser --disabled-password && chown -R appuser /tmp/cmdr
+## Create virtual environment according to Pipfile.lock into user's home as root
+COPY clinical-mdr-api/Pipfile* ./
+RUN HOME=/home/$USER pipenv sync \
+    # clean-up
+    && rm -rf ~/.cache
 
-## run as non root user
-USER appuser
+## Copy the rest of the application owned by root
+COPY clinical-mdr-api/ ./
 
-EXPOSE 5003
+## Byte-code compile application as root
+RUN python -m compileall -f -j 0 $WORKDIR
 
-## run healthcheck on the api endpoint
-HEALTHCHECK CMD curl --fail http://localhost:5003/openapi.json || exit 1
+## Run the rest as non-root user
+USER $USER
 
-CMD ["uvicorn", "clinical_mdr_api.main:app", "--host", "0.0.0.0", "--port", "5003", "--root-path", "/api"]
+## Open up a port to listen on
+EXPOSE $UVICORN_PORT
+
+## Environment variables, use sane defaults, then override them at instantiation
+## Preferred to configure Uvicorn using env vars with UVICORN_ prefix
+ENV UVICORN_PORT="$UVICORN_PORT" \
+    UVICORN_HOST="$UVICORN_HOST" \
+    UVICORN_ROOT_PATH="$UVICORN_ROOT_PATH"
+
+## Run healthcheck on the API endpoint:
+## checks every `interval` seconds, fails if `timeout`,
+## unhealthy status is reached if `retries` number of consecutive failures,
+## but failures does not count within `start-period` seconds of start.
+HEALTHCHECK --start-period=60s --timeout=3s --interval=10s --retries=2 CMD \
+    curl --fail --silent --show-error --max-time 2 \
+    "http://localhost:$UVICORN_PORT/system/healthcheck" \
+    > /dev/null || exit 1
+
+CMD pipenv run uvicorn clinical_mdr_api.main:app
