v0.8.1

diff --git a/neo4j-mdr-db/build-validation.yml b/neo4j-mdr-db/build-validation.yml
--- a/neo4j-mdr-db/build-validation.yml
+++ b/neo4j-mdr-db/build-validation.yml
@@ -14,69 +14,94 @@ trigger:
 pool:
   name: 'clinical-mdr-dev-vmss'
 
-variables:
- - name: python_version
-   value: 3.11
+parameters:
+- name: SERVICE_CONN
+  type: string
+  default: IaCAgent-ClinicalMDR-DEV
 
 jobs:
-- job: 
-  displayName: 'Automated build validation'  
+- job:
+  displayName: 'Validation and license tasks'
   steps:
+
   - checkout: self
     persistCredentials: true
     # Checkout source repos
+
+  - template: pipelines/templates/azure-config.yaml
+
+  - task: AzureCLI@2
+    displayName: Log in to container registry
+    inputs:
+      azureSubscription: ${{parameters.SERVICE_CONN}}
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: >-
+        az acr login -n '$(azmd.acrname)'
+
+  - task: AzureCLI@2
+    displayName: Build docker image
+    inputs:
+      azureSubscription: ${{parameters.SERVICE_CONN}}
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |-
+        docker compose build --progress=plain \
+          --build-arg BUILD_BRANCH='$(Build.SourceBranchName)' \
+          --build-arg BUILD_COMMIT='$(Build.SourceVersion)' \
+          --build-arg BUILD_NUMBER='$(Build.BuildNumber)' \
+          --build-arg PYTHON_IMAGE='$(azmd.acrname).azurecr.io/novo-python-3-11-3-slim:latest' \
+          dev
+
+  # Checkout git branch
   - script: |
+      set -ex
+      
       git fetch -a
 
-      if [[ "$(Build.Reason)" == "PullRequest" ]]; then
-        gitbranch=`echo $(System.PullRequest.SourceBranch) | sed 's/^refs\/heads\///'`
+      if [[ '$(Build.Reason)' == 'PullRequest' ]]; then
+        gitbranch='$(System.PullRequest.SourceBranch)'
       else
-        gitbranch=`echo $(Build.SourceBranch) | sed 's/^refs\/heads\///'`
+        gitbranch='$(Build.SourceBranch)'
       fi
+      gitbranch="${gitbranch#refs/heads/}"
 
       echo "##vso[task.setvariable variable=gitbranch;isOutput=true;]$gitbranch"
 
-      git checkout $gitbranch
+      git checkout "$gitbranch"
       git pull
-    displayName: 'Checkout git branch'
+    displayName: Checkout git branch
     name: gitref
 
-  # Specify python version. The version must be manually installed beforehand so the agent has it available.
-  - task: UsePythonVersion@0
-    inputs:
-      versionSpec: $(python_version)
-      addToPath: true
-      architecture: 'x64'
-
-  # Resolve and install python dependencies
+  # Build SBOM
   - script: |
-      python3 -m venv venv --clear
-      source $(Build.SourcesDirectory)/venv/bin/activate
-      python -m pip install --upgrade pipenv
-      python -m pipenv lock
-      python -m pipenv requirements | tee requirements.txt
-      python -m pipenv install --dev
-      python -m pipenv graph
-    displayName: Setup dependencies
+      set -ex
+      
+      docker compose run --rm dev pipenv run build-sbom > sbom.md
+      tail -n +2 sbom-additional.md >> sbom.md
+    displayName: Build SBOM
 
+  # Commit SBOM
   - script: |
-      pip install -r requirements.txt # duplicated installation step - temporary until sbom is rewritten to work with pipenv
-      find /opt/hostedtoolcache/Python/$(python_version).*/x64/lib/python3.*/site-packages/*.dist*/ -type f -iname "*license*" > files.txt
-      echo "## Third party library licenses descriptions" > sbom.md
-      while read line; do echo $line | rev | cut -d "/" -f2 | rev | cut -d "-" -f1 | awk '{ print "### License for 3rd party library " $1 }' >> sbom.md; echo '```' >> sbom.md && cat $line >> sbom.md && echo ' ' >> sbom.md && echo '```' >> sbom.md; done < files.txt
-      #tail -n +4 sbom.md > tmp && mv tmp sbom.md # include after nnsbom fix
-      tail -n +2 sbom-additional.md > tmp && mv tmp sbom-additional.md
-      cat sbom-additional.md >> sbom.md
-      cat sbom.md
-
-      if [[ "$(Build.SourceBranchName)" != "main" && "$(Build.Reason)" == "PullRequest"  && `git diff --exit-code sbom.md` ]]; then
-        git config --global user.email pipeline@studybuilder.com
-        git config --global user.name "Pipeline $(Build.BuildNumber)"
+      set -ex
+      
+      if [[ '$(Build.Reason)' == 'PullRequest' ]] && ! git diff --exit-code --quiet sbom.md ; then
+        git config --global user.email 'pipeline@studybuilder.com'
+        git config --global user.name 'Pipeline $(Build.BuildNumber)'
+      
+        if [[ '$(Build.SourceBranchName)' != 'main' ]] ; then
+          # Post a comment on pull-request that the SBOM has been changed #
+          pwsh -NoLogo -NonInteractive -File pipelines/scripts/make-sbom-comment-on-pr.ps1 -token '$(System.AccessToken)' -pullRequestId '$(System.PullRequest.PullRequestId)' -projectName '$(System.TeamProject)' -repositoryName '$(Build.Repository.Name)'
+        fi
+      
+        # Commit changes #
         git add sbom.md
-        pwsh -NoLogo -NonInteractive -File CheckSbom.ps1 -token $(System.AccessToken) -pullRequestId $(System.PullRequest.PullRequestId) -projectName $(System.TeamProject) -repositoryName $(Build.Repository.Name)
-        git commit sbom.md -m "Pipeline $(Build.BuildNumber) committed changes to SBOM"
-        git push https://$SYSTEM_ACCESSTOKEN@dev.azure.com/novonordiskit/Clinical-MDR/_git/neo4j-mdr-db $(gitref.gitbranch)
+        git commit sbom.md -m 'Pipeline $(Build.BuildNumber) committed changes to SBOM'
+        gitbranch='$(System.PullRequest.SourceBranch)'
+        gitbranch="${gitbranch#refs/heads/}"
+        git push 'https://$(System.AccessToken)@dev.azure.com/novonordiskit/Clinical-MDR/_git/$(Build.Repository.Name)' "$gitbranch"          
       fi
-    env:
-      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-    displayName: Generate full sbom for neo4j-mdr-db
+    displayName: "Commit sbom.md"
+
+  # Ensure cleanup, including docker shutdown
+  - template: pipelines/templates/docker-cleanup.yml
